name: prj_app_feat_nomadcoder_class
description: 연습작업물 feat. 노마드 코더의 flutter 강의
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #  flutter_tts: '3.0.0'
  http: ^1.0.0
  #  audioplayers: ^0.18.3
  #  audioplayers: ^4.1.0
  #  audioplayers: <=0.18.3
  #  audioplayers: ^0.18.3    #   for web
  #  logger: ^1.3.0
  logger: ^1.4.0
  #  cupertino_icons: ^1.0.2
  clipboard: ^0.1.3
  timer_builder: ^2.0.0
  date_format: ^2.0.7
  url_launcher: ^6.1.12
  path_provider: ^2.0.15
  permission_handler:
  shared_preferences:  # web 불가
  localstorage: # Web 가능 # 로컬 데이터를 저장용
  flutter_session_manager: # Web 가능 # 로컬 데이터를 저장용
#  indexed_db: # Web 가능 # 로컬 데이터를 저장용 # 내장라이브러리 인듯. 여기서 dependency 추가 하면 안됨.
#  dio_cookie_manager: ^3.1.0
  #  flutter_tts: ^3.7.0
  flutter_tts: 
  flutter_provider: ^2.1.0 #위젯간 데이터 통신용
  linkify: ^5.0.0
#  webview_flutter: ^4.2.2
  webview_flutter:
#  firebase_core:
#  cloud_firestore: #firebase 의 DB
#  video_player: ^2.7.0
  video_player:
#  image_picker: ^ 1.0.1
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/images/random_numbers/


  fonts:
    - family: sunFlower
      fonts:
        - asset: asset/fonts/Sunflower-Light.ttf
        - asset: asset/fonts/Sunflower-Medium.ttf
          weight: 500
        - asset: asset/fonts/Sunflower-Bold.ttf
          weight: 700

    - family: Parisienne
      fonts:
        - asset: asset/fonts/Parisienne-Regular.ttf

    - family: Raleway
      fonts:
        - asset: asset/fonts/Raleway-VariableFont_wght.ttf
          weight: 200
        - asset: asset/fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: asset/fonts/RobotoMono-VariableFont_wght.ttf
          weight: 200
        - asset: asset/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic
    - family: RalewayDots
      fonts:
        - asset: asset/fonts/RalewayDots-Regular.ttf


  # 커스텀폰트
  # see https://flutter.dev/custom-fonts/#from-packages


